PredictPriceWeb/Models/ErrorViewModel.cs
namespace PredictPriceWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PredictPriceWeb/Models/PredictStockPrice.cs
using CsvHelper.Configuration.Attributes;
using Microsoft.ML.Data;

namespace PredictPriceWeb.Models
{
    public class PredictStockPrice
    {


        [Index(0)]
        public string stockId { get; set; }
        [Index(1)]
        public string timeStamp { get; set; }

        [Index(3)]
        [VectorType(2)]
        public decimal stockPrice
        {
            get; set;
        }
    }

    public class Predict
    {
        public IEnumerable<IFormFile>? files { get; set; }
        public IEnumerable<PredictStockPrice>? stocks { get; set; }
    }

    public class ForecastResult
    {
        public PredictStockPrice[] foreCast { get; set; }
    }
}

PredictPriceWeb/Controllers/PredictScoreController.cs
using Microsoft.AspNetCore.Mvc;

namespace PredictPriceWeb.Controllers
{
    public class PredictScoreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PredictPriceWeb/Views/PredictScore/Index.cshtml
@model PredictPriceWeb.Models.Predict
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Stock Prediction</h1>
    <div id="sectionFreeText">
        <input type="file" id="Files" name="Files" asp-for="files" webkitdirectory multiple class="btn btn-primary shadow-lg" />
    </div><br>
    <div action="submit">
        <a href="" title="Predict" data-bs-toggle="tooltip" data-toggle="tooltip" class="btn btn-dark" onclick="PredictScore() ;return false">
         Predict Score
        </a>

    </div>
</div>

@section scripts {

    <script src="~/js/predictscore.js"></script>
}

PredictPriceWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PredictPriceWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PredictPriceWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="PredictScore" asp-action="Index">PredictPriceWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PredictScore" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PredictScore" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PredictPriceWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>